version: 2.1
orbs:
  php: circleci/php@1.1.0 # PHP Orbを追加
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers # The primary container where steps are run
      - image: cimg/mysql:8.0
    environment:
      - DB_CONNECTION: mysql_test
    working_directory: ~/ci-demo

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - php/install-packages # PHP Orbからinstall-packagesコマンドを使用
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
workflows:
  version: 2.1
  install:
    jobs:
      - php/install_composer_packages # PHP Orbからinstall_composer_packagesジョブを使用
