version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:7.4.14-browsers

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: 'Prepare Environment'
          command: |
            sudo apt update
            sudo apt-get install -y php-zip

      - run:
          name: 'Create Environment file'
          command: |
            mv ~/coachtech-flea-market-app/src/.env.testing ~/coachtech-flea-market-app/src/.env

      - run:
          name: 'Install Dependencies'
          command: composer install -n --prefer-dist

      - run:
          name: 'Run Tests'
          command: ./vendor/bin/phpunit tests
