version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers # The primary container where steps are run
        #environment:
      - image: circleci/mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - APP_KEY: base64:UdiSS/AgMKN0J0a//YjvyMWg5IhC1VvbEYfh+G4Rb1Q=
          - DB_CONNECTION: mysql_test
          - DB_HOST: 127.0.0.1
          - DB_PORT: 3306
          - DB_DATABASE: demo_test
          - DB_USERNAME: root
          - DB_PASSWORD: root
          - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/ci-demo

    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
      - run:
          name: Docker php extensions install
          command: |
          sudo docker-php-ext-install pdo_mysql
          sudo docker-php-ext-enable pdo_mysql
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./src
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      - run:
          name: Run Migration & Seeding
          command: php ./src/artisan migrate --seed --env=testing --force
      #      - run:
      #          name: Run seeders
      #          command: php ./src/artisan db:seed --env=testing --force
      - run:
          name: Run PHPUnit
          command: .src/vendor/bin/phpunit --configuration=./src/phpunit.xml

workflows:
  version: 2.1
  install:
    jobs:
      - build
