version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/php:7.4.26-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root

    environment:
      - DB_CONNECTION: demo_test

    working_directory: ~/coachtech-flea-market-app/src

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: 'Prepare Environment'
          command: |
            sudo apt update
            sudo apt-get install -y php-zip

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: 'Install Dependencies'
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: 'Run Tests'
          command: ./vendor/bin/phpunit
