version: 2.1

jobs:
  build:
    docker:
      - image: circle/php:8.0
    steps:
      - checkout
      - run: echo "this is the build job"

  test:
    docker:
      - image: circle/php:8.0
    steps:
      - checkout
      - run: echo "this is the test job"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
