version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/php:7.4.26-browsers
      - image: cimg/cimg/mysql:8.0
    environment:
      - DB_CONNECTION: mysql_test
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: demo_test
          MYSQL_HOST: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: root

    working_directory: ~/ci-demo

    steps:
      - browser-tools/install-browser-tools
      - checkout

      - run:
          name: 'Prepare Environment'
          command: |
            sudo apt update
            sudo apt-get install -y php-zip

      - run:
          name: 'Install Dependencies'
          command: composer install -n --prefer-dist

      - run:
          name: 'Run Tests'
          command: ./vendor/bin/phpunit
